export const LATAM_COUNTRIES = [
  { value: "mx", label: "México" },
  { value: "co", label: "Colombia" },
  { value: "ar", label: "Argentina" },
  { value: "cl", label: "Chile" },
  { value: "pe", label: "Perú" },
  { value: "ec", label: "Ecuador" },
  { value: "ve", label: "Venezuela" },
  { value: "gt", label: "Guatemala" },
  { value: "cu", label: "Cuba" },
  { value: "bo", label: "Bolivia" },
  { value: "hn", label: "Honduras" },
  { value: "py", label: "Paraguay" },
  { value: "sv", label: "El Salvador" },
  { value: "ni", label: "Nicaragua" },
  { value: "cr", label: "Costa Rica" },
  { value: "pa", label: "Panamá" },
  { value: "uy", label: "Uruguay" },
  { value: "do", label: "República Dominicana" },
  { value: "br", label: "Brasil" },
  { value: "pr", label: "Puerto Rico" },
];

export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  "México": "mx",
  "Colombia": "co",
  "Argentina": "ar",
  "Chile": "cl",
  "Perú": "pe",
  "Ecuador": "ec",
  "Venezuela": "ve",
  "Guatemala": "gt",
  "Cuba": "cu",
  "Bolivia": "bo",
  "Honduras": "hn",
  "Paraguay": "py",
  "El Salvador": "sv",
  "Nicaragua": "ni",
  "Costa Rica": "cr",
  "Panamá": "pa",
  "Uruguay": "uy",
  "República Dominicana": "do",
  "Brasil": "br",
  "Puerto Rico": "pr",
};

export const SUBJECTS = [
  "Matemáticas",
  "Física",
  "Química",
  "Biología",
  "Historia",
  "Geografía",
  "Literatura",
  "Inglés",
  "Portugués",
  "Francés",
  "Programación",
  "Economía",
  "Contabilidad",
  "Derecho",
  "Psicología",
  "Filosofía",
  "Música",
  "Arte",
  "Estadística",
  "Cálculo",
];
